/**
 * Auto-update host (F-slice #2) — bridges the frontend's Tauri updater
 * contract onto electron-updater, per the competitor-survey selection
 * (memory `reference-electron-autoupdate-across-competitors`):
 * `electron-updater` + generic provider pointed at the EXISTING Aliyun OSS
 * bucket that already serves the Tauri `latest.json` — the feed just gains a
 * `latest-mac.yml` (generated by electron-builder at dist time, never
 * hand-written: the sha512 must be computed from the final artifact).
 *
 * ## Frontend contract (verbatim from @tauri-apps/plugin-updater dist-js)
 * src/core/updates/checker.ts calls exactly two plugin paths:
 *  - `check()` → invoke('plugin:updater|check', {...}) → metadata
 *    `{ rid, currentVersion, version, date, body, rawJson }` or null.
 *  - `Update.downloadAndInstall(onEvent)` →
 *    invoke('plugin:updater|download_and_install', { onEvent: Channel, rid })
 *    with Started/Progress/Finished events:
 *      { event: 'Started',  data: { contentLength?: number } }
 *      { event: 'Progress', data: { chunkLength: number } }
 *      { event: 'Finished' }
 * Channel delivery rides the same `tauri:callback` bridge as fs watch
 * (fsWatchHost.cjs header documents the `{ index, message }` payload shape).
 * `Update.close()` → plugin:resources|close, which fsWatchHost owns; an
 * updater rid is unknown to its table so the close is a harmless no-op.
 * The two-step `download`/`install` commands are NOT used by the frontend
 * and have no electron-updater equivalent (install happens at quit) — they
 * reject with a clear error rather than pretending.
 *
 * ## Install-at-restart semantics
 * Tauri's downloadAndInstall installs in place and the app keeps running
 * until the user clicks "restart" (plugin:process|restart). electron-updater
 * separates download (here) from install (quitAndInstall). To preserve the
 * frontend flow, desktopHost's processRestart consults
 * `consumePendingInstall()` — when a downloaded update is pending, restart
 * becomes `autoUpdater.quitAndInstall()` instead of plain relaunch.
 * `autoInstallOnAppQuit` stays on as a safety net (normal quit also applies
 * the update).
 *
 * ## Feed resolution
 *  - Packaged: electron-builder embeds `app-update.yml` (from
 *    electron-builder.yml's `publish` block) → generic provider at the OSS
 *    bucket. Real download/install still needs a signed build (F11 remainder).
 *  - Dev/harness: armed only when ABU_UPDATER_FEED_URL is set (e.g. the mock
 *    feed in electron/spike/updaterVerify.cjs) — forceDevUpdateConfig plus an
 *    explicit generic feed. Without it, check() reports null (updater idle in
 *    dev, matching the pre-slice behavior).
 */
'use strict';

const { app } = require('electron');

/** Sentinel returned when `cmd` isn't one of the updater family. */
const UPDATER_MISS = Symbol('updater-dispatch-miss');

/** Production feed — the bucket that already serves the Tauri latest.json. */
const OSS_FEED_URL = 'https://abu-agent.oss-cn-beijing.aliyuncs.com/';

/** @type {import('electron-updater').AppUpdater | null} */
let updater = null;
let configured = false;
/** rid handed to the renderer's Update resource; single pending check result. */
let nextRid = 90001;
/** Set once download_and_install completed; consumed by processRestart. */
let pendingInstall = false;

function log(msg) {
  console.log(`[updaterHost] ${msg}`);
}

/**
 * Lazy singleton: `require('electron-updater')` is deferred so plain-Node
 * harnesses that never touch updater commands don't pay for (or crash on)
 * the electron-updater import.
 */
function getUpdater() {
  if (configured) return updater;
  configured = true;

  const feedOverride = process.env.ABU_UPDATER_FEED_URL;
  if (!app.isPackaged && !feedOverride) {
    // Dev without an explicit feed: stay idle. electron-updater would refuse
    // anyway ("application is not packed"), just noisier.
    log('dev shell without ABU_UPDATER_FEED_URL — updater idle, check() reports no update');
    updater = null;
    return updater;
  }

  const { autoUpdater } = require('electron-updater');
  autoUpdater.autoDownload = false; // the frontend drives download explicitly
  autoUpdater.autoInstallOnAppQuit = true;
  autoUpdater.logger = {
    info: (m) => log(`electron-updater: ${m}`),
    warn: (m) => console.warn(`[updaterHost] electron-updater: ${m}`),
    error: (m) => console.error(`[updaterHost] electron-updater: ${m}`),
    debug: () => {},
  };
  if (feedOverride) {
    // NOT setFeedURL: that only swaps the check-time provider —
    // downloadUpdate still resolves `configOnDisk` (for updaterCacheDirName,
    // AppUpdater.js ~545), which in dev reads `<appPath>/dev-app-update.yml`
    // and ENOENTs. Writing a real config file and pointing updateConfigPath
    // at it feeds BOTH paths from one source.
    const fs = require('node:fs');
    const os = require('node:os');
    const path = require('node:path');
    const configPath = path.join(os.tmpdir(), `abu-updater-dev-config-${process.pid}.yml`);
    fs.writeFileSync(
      configPath,
      `provider: generic\nurl: ${feedOverride}\nupdaterCacheDirName: abu-updater-dev-cache\n`,
      'utf8'
    );
    autoUpdater.forceDevUpdateConfig = true;
    autoUpdater.updateConfigPath = configPath;
    log(`feed override via ABU_UPDATER_FEED_URL: ${feedOverride} (config at ${configPath})`);
  }
  // Packaged with no override: the embedded app-update.yml (electron-builder
  // `publish` block → generic provider at OSS_FEED_URL) is picked up
  // automatically; nothing to do here.

  updater = autoUpdater;
  return updater;
}

/** Map electron-updater releaseNotes (string | ReleaseNoteInfo[] | null) to the single string Tauri's `body` carries. */
function notesToBody(releaseNotes) {
  if (typeof releaseNotes === 'string') return releaseNotes;
  if (Array.isArray(releaseNotes)) {
    return releaseNotes.map((n) => (typeof n === 'string' ? n : n && n.note ? n.note : '')).join('\n');
  }
  return '';
}

/** plugin:updater|check → Update metadata or null. */
async function check() {
  const au = getUpdater();
  if (!au) return null;
  const result = await au.checkForUpdates();
  if (!result || !result.isUpdateAvailable) return null;
  const info = result.updateInfo;
  return {
    rid: nextRid++,
    currentVersion: app.getVersion(),
    version: info.version,
    date: info.releaseDate || '',
    body: notesToBody(info.releaseNotes),
    rawJson: JSON.parse(JSON.stringify(info)),
  };
}

/** Parse a Channel's wire form ("__CHANNEL__:<id>") into its numeric callback id (see fsWatchHost). */
function parseChannelId(onEvent) {
  if (typeof onEvent !== 'string') return null;
  const m = /^__CHANNEL__:(\d+)$/.exec(onEvent);
  return m ? Number(m[1]) : null;
}

/**
 * plugin:updater|download_and_install → download via electron-updater with
 * Tauri-shaped progress events; the actual install applies at restart/quit
 * (see header). Rejects on download/verification failure (e.g. sha512
 * mismatch) so the frontend's catch path resets its progress UI.
 * @param {Record<string, unknown>} a
 * @param {Electron.IpcMainInvokeEvent | undefined} event
 */
async function downloadAndInstall(a, event) {
  const au = getUpdater();
  if (!au) throw new Error('updater not armed (dev shell without ABU_UPDATER_FEED_URL)');

  const callbackId = parseChannelId(a.onEvent);
  const sender = event && event.sender;
  let index = 0;
  const send = (message) => {
    if (callbackId === null || !sender || sender.isDestroyed()) return;
    sender.send('tauri:callback', { id: callbackId, payload: { index: index++, message } });
  };

  let started = false;
  const onProgress = (p) => {
    if (!started) {
      started = true;
      send({ event: 'Started', data: { contentLength: p.total } });
    }
    send({ event: 'Progress', data: { chunkLength: p.delta } });
  };
  au.on('download-progress', onProgress);
  try {
    await au.downloadUpdate();
    pendingInstall = true;
    send({ event: 'Finished' });
  } finally {
    au.removeListener('download-progress', onProgress);
  }
  return null;
}

/**
 * Consumed by desktopHost's processRestart: when true, restart must go
 * through quitAndInstall so the downloaded update actually applies.
 * Returns the updater to call quitAndInstall on, or null.
 */
function consumePendingInstall() {
  if (!pendingInstall || !updater) return null;
  pendingInstall = false;
  return updater;
}

/**
 * Map a `plugin:updater|*` command. Returns UPDATER_MISS for anything else so
 * tauriHost falls through to its default dispatch.
 * @param {string} cmd
 * @param {{ args?: Record<string, unknown>, event?: Electron.IpcMainInvokeEvent }} payload
 */
function updaterDispatch(cmd, { args, event } = {}) {
  const a = args || {};
  switch (cmd) {
    case 'plugin:updater|check':
      return check();
    case 'plugin:updater|download_and_install':
      return downloadAndInstall(a, event);
    case 'plugin:updater|download':
    case 'plugin:updater|install':
      // No electron-updater equivalent of Tauri's two-step download/install
      // (install happens at quit). The frontend only ever calls
      // download_and_install; fail loudly rather than half-pretending.
      return Promise.reject(
        new Error(`${cmd}: not supported in the Electron shell — use downloadAndInstall`)
      );
    default:
      return UPDATER_MISS;
  }
}

module.exports = { updaterDispatch, consumePendingInstall, UPDATER_MISS };
