import {
  Archive, ArrowLeft, AtSign, Brain, Check, CheckSquare, ChevronDown, ChevronRight, ChevronsUpDown, ChevronUp, CircleCheck, CircleHelp, CircleX,
  Code, Compass, Copy, Download, Ellipsis, ExternalLink, Eye, File, FileCode, FileImage, FileJson, FileSearch, FileText, FileType2, FileWarning, FileX,
  Folder, FolderInput, FolderOpen, Globe, ImageOff, Inbox, Info, LayoutGrid, ListTree, LoaderCircle, LogIn, LogOut, Maximize2, MessageCircle, MessageSquare,
  MessageSquarePlus, Minimize2, Minus, Palette, PanelLeft, PanelRight, Paperclip, Pencil, Pin, PinOff, Plus, Presentation, Puzzle, Redo2, RefreshCw, RotateCcw,
  Search, Settings, Share, Sheet, Sparkles, SquarePen, ThumbsDown, ThumbsUp, Trash2, TriangleAlert, Undo2, UserRound, UsersRound, Wand2, Workflow, X, ZoomIn, ZoomOut,
  type LucideIcon,
} from 'lucide-react';

// One icon per standard action across the whole app (Apple HIG "Standard icons").
// Add an entry here before using a new action icon anywhere else.
export const AppIcons = {
  copy: Copy,
  delete: Trash2,
  share: Share,
  more: Ellipsis,
  add: Plus,
  close: X,
  search: Search,
  settings: Settings,
  done: Check,
  rename: Pencil,
  compose: SquarePen,
  folder: Folder,
  attach: Paperclip,
  undo: Undo2,
  redo: Redo2,
  download: Download,
  openExternal: ExternalLink,
  retry: RefreshCw,
  expand: ChevronDown,
  disclose: ChevronRight,
  success: CircleCheck,
  warning: TriangleAlert,
  error: CircleX,
  info: Info,
  loading: LoaderCircle,
  mixed: Minus,
  selectorChevrons: ChevronsUpDown,
  sidebar: PanelLeft,
  rightPanel: PanelRight,
  back: ArrowLeft,
  import: FolderInput,
  remove: Minus,
  fileTree: ListTree,
  // Sidebar destinations
  team: UsersRound,
  extensions: Puzzle,
  automation: Workflow,
  todos: CheckSquare,
  inbox: Inbox,
  webPage: Globe,
  // Projects and task rows
  folderOpen: FolderOpen,
  pin: Pin,
  unpin: PinOff,
  archive: Archive,
  conversation: MessageSquare,
  // App switcher
  discoverApps: Compass,
  appMarket: LayoutGrid,
  createApp: Wand2,
  // Account menu
  account: UserRound,
  language: Globe,
  appearance: Palette,
  help: CircleHelp,
  feedback: MessageCircle,
  restart: RotateCcw,
  signIn: LogIn,
  signOut: LogOut,
  // Chat: message content
  collapse: ChevronUp,
  viewSource: Code,
  preview: Eye,
  enlarge: Maximize2,
  zoomIn: ZoomIn,
  zoomOut: ZoomOut,
  // Chat: messages
  thinking: Brain,
  skill: Wand2,
  mention: AtSign,
  file: FileText,
  fileCode: FileCode,
  fileImage: FileImage,
  fileJson: FileJson,
  fileSlides: Presentation,
  fileSheet: Sheet,
  fileDocument: FileType2,
  filePdf: FileSearch,
  fileGeneric: File,
  fileMissing: FileX,
  fileNotBackedUp: FileWarning,
  imageMissing: ImageOff,
  thumbsUp: ThumbsUp,
  thumbsDown: ThumbsDown,
  newTaskFromMessage: MessageSquarePlus,
  compact: Minimize2,
  sparkles: Sparkles,
} as const satisfies Record<string, LucideIcon>;

export type AppIconName = keyof typeof AppIcons;
