import {
  Activity, AppWindow, Archive, ArrowLeft, ArrowRight, ArrowUp, ArrowUpRight, AtSign, Ban, BarChart3, Bot, Brain, Building2, Check, CheckSquare, ChevronDown, ChevronLeft, ChevronRight, ChevronsUpDown, ChevronUp, Chrome, CircleCheck, CircleHelp,
  CircleStop, CircleX, Clock, Code, Compass, Copy, CornerDownRight, Download, Ellipsis, ExternalLink, Eye, EyeOff, File, FileCode, FileImage, FileJson, FilePen, FilePlus,
  FileSearch, FileText, FileType2, FileWarning, FileX, FlaskConical, Folder, FolderInput, FolderOpen, FolderPlus, Globe, Hand, Hash, Heart, History, ImageIcon, ImageOff, Inbox, Info, LayoutGrid, Lightbulb, Link2, ListChecks, ListTree,
  LoaderCircle, Lock, LogIn, LogOut, Maximize2, MessageCircle, MessageSquare, MessageSquarePlus, Minimize2, Minus, Monitor, MonitorCog, MousePointer2, Palette, PanelLeft, PanelRight,
  Paperclip, PawPrint, Pencil, PenLine, Pin, PinOff, Play, Plug, Plus, Presentation, Puzzle, Radio, Redo2, RefreshCw, RotateCcw, RotateCw, Save, Scan, ScanEye, ScanLine, Search, Settings, Settings2, Share, Sheet, Shield, ShieldAlert, ShieldCheck,
  SlidersHorizontal, Sparkles, Square, SquareDashedMousePointer, SquarePen, Star, Terminal, ThumbsDown, ThumbsUp, Trash2, TriangleAlert, Undo2, UserCheck, UserRound, UsersRound,
  Wand2, Workflow, Wrench, X, Zap, ZoomIn, ZoomOut,
  type LucideIcon,
} from 'lucide-react';

// One icon per standard action across the whole app (Apple HIG "Standard icons").
// Add an entry here before using a new action icon anywhere else.
export const AppIcons = {
  copy: Copy,
  delete: Trash2,
  share: Share,
  more: Ellipsis,
  add: Plus,
  close: X,
  search: Search,
  settings: Settings,
  done: Check,
  rename: Pencil,
  compose: SquarePen,
  folder: Folder,
  attach: Paperclip,
  undo: Undo2,
  redo: Redo2,
  download: Download,
  openExternal: ExternalLink,
  retry: RefreshCw,
  expand: ChevronDown,
  disclose: ChevronRight,
  success: CircleCheck,
  warning: TriangleAlert,
  error: CircleX,
  info: Info,
  loading: LoaderCircle,
  mixed: Minus,
  selectorChevrons: ChevronsUpDown,
  sidebar: PanelLeft,
  rightPanel: PanelRight,
  back: ArrowLeft,
  import: FolderInput,
  remove: Minus,
  fileTree: ListTree,
  // Sidebar destinations
  team: UsersRound,
  extensions: Puzzle,
  automation: Workflow,
  todos: CheckSquare,
  inbox: Inbox,
  webPage: Globe,
  // Projects and task rows
  folderOpen: FolderOpen,
  pin: Pin,
  unpin: PinOff,
  archive: Archive,
  conversation: MessageSquare,
  // App switcher
  discoverApps: Compass,
  appMarket: LayoutGrid,
  createApp: Wand2,
  // Account menu
  account: UserRound,
  language: Globe,
  appearance: Palette,
  help: CircleHelp,
  feedback: MessageCircle,
  restart: RotateCcw,
  signIn: LogIn,
  signOut: LogOut,
  // Chat: message content
  collapse: ChevronUp,
  viewSource: Code,
  preview: Eye,
  enlarge: Maximize2,
  zoomIn: ZoomIn,
  zoomOut: ZoomOut,
  // Chat: messages
  thinking: Brain,
  skill: Wand2,
  mention: AtSign,
  file: FileText,
  fileCode: FileCode,
  fileImage: FileImage,
  fileJson: FileJson,
  fileSlides: Presentation,
  fileSheet: Sheet,
  fileDocument: FileType2,
  filePdf: FileSearch,
  fileGeneric: File,
  fileMissing: FileX,
  fileNotBackedUp: FileWarning,
  imageMissing: ImageOff,
  thumbsUp: ThumbsUp,
  thumbsDown: ThumbsDown,
  newTaskFromMessage: MessageSquarePlus,
  compact: Minimize2,
  sparkles: Sparkles,
  // Chat: tool steps
  tool: Wrench,
  terminal: Terminal,
  plug: Plug,
  clock: Clock,
  fileRead: FileSearch,
  fileEdit: FilePen,
  fileCreate: FilePlus,
  stopped: CircleStop,
  awaitingAnswer: MessageSquare,
  // Chat: cards
  monitor: Monitor,
  stop: Square,
  block: Ban,
  shield: ShieldAlert,
  userCheck: UserCheck,
  plan: ListChecks,
  // Chat: approvals and notices
  hint: Lightbulb,
  queued: CornerDownRight,
  channel: Hash,
  capability: Shield,
  trigger: Zap,
  sandbox: MonitorCog,
  sandboxReady: ShieldCheck,
  continue: Play,
  openIn: ArrowUpRight,
  previous: ChevronLeft,
  customAnswer: Pencil,
  // Chat: composer selectors
  favorite: Star,
  permissionAsk: Hand,
  permissionReview: ScanEye,
  // Chat: composer
  send: ArrowUp,
  // Chat: frame
  history: History,
  chart: BarChart3,
  write: PenLine,
  link: Link2,
  // Right panel: tabs
  agent: Bot,
  // Right panel: preview
  reload: RotateCw,
  selectElement: SquareDashedMousePointer,
  exitFullscreen: Minimize2,
  saveAs: Save,
  commentToChat: MessageSquarePlus,
  quoteToChat: MessageSquare,
  // Right panel: file renderers
  rotateLeft: RotateCcw,
  rotateRight: RotateCw,
  fitView: Scan,
  fitWidth: ScanLine,
  next: ChevronRight,
  // Right panel: browser
  forward: ArrowRight,
  // Right panel: experts
  appendInstruction: MessageSquarePlus,
  // Right panel: file tree
  newFolder: FolderPlus,
  // Settings: navigation
  preferences: SlidersHorizontal,
  capabilities: Zap,
  security: Shield,
  imChannels: Radio,
  labs: FlaskConical,
  models: Settings2,
  memory: Brain,
  soul: Heart,
  pet: PawPrint,
  diagnostic: Activity,
  enterprise: Building2,
  // Settings: security
  appWindow: AppWindow,
  // Settings: capabilities
  chrome: Chrome,
  computerUse: MonitorCog,
  screenRead: Eye,
  uiControl: MousePointer2,
  // Settings: models
  showSecret: Eye,
  hideSecret: EyeOff,
  imageGen: ImageIcon,
  // Settings: memory
  private: Lock,
  allProjects: Globe,
  tidyUp: ListChecks,
} as const satisfies Record<string, LucideIcon>;

export type AppIconName = keyof typeof AppIcons;
