import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import test from 'node:test';
import { collectInventory, renderBlock, applyBlock, START, END } from './test-inventory.mjs';

function fixtureRepo() {
  const root = mkdtempSync(path.join(tmpdir(), 'abu-inventory-'));
  const touch = (rel) => {
    mkdirSync(path.dirname(path.join(root, rel)), { recursive: true });
    writeFileSync(path.join(root, rel), '');
  };
  touch('src/a.test.ts');
  touch('src/b.test.tsx');
  touch('src/c.integration.test.ts');
  touch('src/d.contract.test.ts');
  touch('src/__tests__/quarantine/q.test.ts');
  touch('scripts/s.test.ts');
  touch('scripts/w.test.mjs');
  touch('electron/e.test.cjs');
  touch('electron/e2.test.ts');
  touch('e2e/web.spec.ts');
  touch('tests/e2e/desktop.spec.ts');
  touch('node_modules/x/n.test.ts'); // must be ignored
  return root;
}

test('collectInventory counts each layer by filename convention', () => {
  const inv = collectInventory(fixtureRepo());
  assert.deepEqual(inv, {
    unit: 4, // a.test.ts, b.test.tsx, scripts/s.test.ts, electron/e2.test.ts
    integration: 1,
    contract: 1,
    quarantine: 1,
    e2eWeb: 1,
    e2eElectron: 1,
    nodeTest: 2, // scripts/w.test.mjs, electron/e.test.cjs
  });
});

test('renderBlock produces a markdown table wrapped in markers', () => {
  const block = renderBlock({ unit: 4, integration: 1, contract: 1, quarantine: 1, e2eWeb: 1, e2eElectron: 1, nodeTest: 2 });
  assert.ok(block.startsWith(START));
  assert.ok(block.trimEnd().endsWith(END));
  assert.match(block, /\| Unit \(`\*\.test\.ts\(x\)`, Vitest\) \| 4 \|/);
  assert.match(block, /generated by `npm run test:inventory`/);
});

test('applyBlock replaces an existing block and leaves the rest untouched', () => {
  const md = `# T\n\nintro\n\n${START}\nold\n${END}\n\nafter\n`;
  const out = applyBlock(md, `${START}\nnew\n${END}`);
  assert.equal(out, `# T\n\nintro\n\n${START}\nnew\n${END}\n\nafter\n`);
});

test('applyBlock throws when markers are missing', () => {
  assert.throws(() => applyBlock('no markers here', `${START}\nx\n${END}`), /markers not found/);
});

test('--check exits non-zero when the block is stale', () => {
  const root = fixtureRepo();
  writeFileSync(path.join(root, 'TESTING.md'), `# T\n${START}\nstale\n${END}\n`);
  const r = spawnSync(process.execPath, [path.resolve('scripts/test-inventory.mjs'), '--check', '--root', root], { encoding: 'utf8' });
  assert.equal(r.status, 1);
  assert.match(r.stdout + r.stderr, /stale/i);
  const w = spawnSync(process.execPath, [path.resolve('scripts/test-inventory.mjs'), '--write', '--root', root], { encoding: 'utf8' });
  assert.equal(w.status, 0);
  assert.match(readFileSync(path.join(root, 'TESTING.md'), 'utf8'), /\| Unit/);
  const c = spawnSync(process.execPath, [path.resolve('scripts/test-inventory.mjs'), '--check', '--root', root], { encoding: 'utf8' });
  assert.equal(c.status, 0);
});
